default:
  tags:
    - CREMI
    - Noble/Numbat

stages:
  - build
  - test
  - coverage

build-job1:
  stage: build
  script:
    - ./src/install_deps.sh
    - source venv/bin/activate
    - ./src/install_deps.sh
    - pip install coverage
    - pip install pyvirtualdisplay
  
test-job1:
  stage: test
  script:
    - python3 -m unittest discover -s tests -p "test_*.py"

coverage-job1:
  stage: coverage
  script:
    - python3 -m coverage run -m unittest discover -s tests -p "test_*.py"
    - python3 -m coverage report -m -i